# Generated by Django 4.2.21 on 2025-10-28 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_add_sale_periods_and_new_models'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromotionProduct',
        ),
    ]
