# Generated by Django 4.2.21 on 2025-10-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_delete_promotionproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active_promotion_name',
            field=models.CharField(blank=True, help_text='Назва акції для відображення на бейджі', max_length=100, verbose_name='Назва активної акції'),
        ),
        migrations.DeleteModel(
            name='SalePromotion',
        ),
    ]
