# Generated by Django 4.2.21 on 2025-11-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_brand_product_product_group_product_purpose'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', 'is_active'], name='products_pr_brand_i_8f789e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_group', 'is_active'], name='products_pr_product_95e7fc_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['purpose', 'is_active'], name='products_pr_purpose_ca92c6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['retail_price'], name='products_pr_retail__ead01f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['stock'], name='products_pr_stock_4d23d5_idx'),
        ),
    ]
