# Generated by Django 4.2.21 on 2025-11-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_products_pr_brand_i_8f789e_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='product',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_brand_i_8f789e_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_product_95e7fc_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_purpose_ca92c6_idx',
        ),
        migrations.RemoveField(
            model_name='categoryfilterconfig',
            name='show_brand_filter',
        ),
        migrations.RemoveField(
            model_name='categoryfilterconfig',
            name='show_group_filter',
        ),
        migrations.RemoveField(
            model_name='categoryfilterconfig',
            name='show_purpose_filter',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_group',
        ),
        migrations.RemoveField(
            model_name='product',
            name='purpose',
        ),
        migrations.AddField(
            model_name='product',
            name='characteristics',
            field=models.TextField(blank=True, help_text="Характеристики товару (виробник, об'єм, тип тощо)", verbose_name='Характеристики'),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
        migrations.DeleteModel(
            name='ProductGroup',
        ),
        migrations.DeleteModel(
            name='ProductPurpose',
        ),
    ]
