# Generated by Django 4.2.21 on 2025-11-09 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_productattribute_product_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_is_acti_48ea0f_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_top',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'is_sale', 'is_new'], name='products_pr_is_acti_84f450_idx'),
        ),
    ]
