# Generated by Django 4.2.21 on 2025-11-09 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_is_top_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_price_3_qty',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Акційна ціна при покупці від 3 штук', max_digits=10, null=True, verbose_name='Акційна ціна від 3 шт'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price_5_qty',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Акційна ціна при покупці від 5 штук', max_digits=10, null=True, verbose_name='Акційна ціна від 5 шт'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_wholesale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Акційна ціна для оптових клієнтів', max_digits=10, null=True, verbose_name='Акційна оптова ціна'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Акційна ціна для роздрібних покупців', max_digits=10, null=True, verbose_name='Акційна роздрібна ціна'),
        ),
    ]
