# Generated by Django 4.2.21 on 2025-11-17 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_remove_promocode_description_and_more'),
        ('products', '0016_category_products_ca_parent__1cafc9_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='current_promotion',
            field=models.ForeignKey(blank=True, help_text='Акція яка зараз застосована до цього товару', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_products', to='promotions.promotion', verbose_name='Поточна акція'),
        ),
    ]
