# Generated by Django 4.2.24 on 2025-11-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_promotion_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailClient',
            fields=[
            ],
            options={
                'verbose_name': 'Роздрібний клієнт',
                'verbose_name_plural': 'Роздрібні клієнти',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.order',),
        ),
        migrations.AddField(
            model_name='order',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='По-батькові'),
        ),
    ]
