# Generated by Django 4.2.21 on 2025-11-08 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_retailclient_order_middle_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва розсилки')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема листа')),
                ('content', models.TextField(verbose_name='Контент листа')),
                ('image', models.ImageField(blank=True, null=True, upload_to='email_campaigns/', verbose_name='Зображення')),
                ('recipients', models.JSONField(default=list, help_text='Список типів отримувачів', verbose_name='Отримувачі')),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('scheduled', 'Заплановано'), ('sending', 'Відправляється'), ('sent', 'Відправлено'), ('failed', 'Помилка')], default='draft', max_length=20, verbose_name='Статус')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Час відправки')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='Відправлено')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='Помилок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Відправлено')),
            ],
            options={
                'verbose_name': 'Email розсилка',
                'verbose_name_plural': 'Email розсилки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name="Ім'я")),
                ('source', models.CharField(choices=[('newsletter', 'Підписка на розсилку'), ('registered', 'Зареєстрований користувач'), ('order', 'Замовлення без реєстрації')], max_length=20, verbose_name='Джерело')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('is_wholesale', models.BooleanField(default=False, verbose_name='Оптовий клієнт')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата додавання')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Email адреса',
                'verbose_name_plural': 'Email адреси',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='RetailClient',
        ),
        migrations.AddIndex(
            model_name='emailsubscriber',
            index=models.Index(fields=['email', 'source'], name='orders_emai_email_75d855_idx'),
        ),
        migrations.AddIndex(
            model_name='emailsubscriber',
            index=models.Index(fields=['is_active', 'source'], name='orders_emai_is_acti_af4626_idx'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Створив'),
        ),
    ]
