# Generated by Django 4.2.21 on 2025-11-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_emailcampaign_emailsubscriber_delete_retailclient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name="Ім'я"),
        ),
        migrations.DeleteModel(
            name='EmailSubscriber',
        ),
    ]
