# Generated by Django 4.2.21 on 2025-11-10 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_update_newsletter_and_remove_emailsubscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(blank=True, choices=[('warehouse', 'Відділення'), ('postomat', 'Поштомат')], default='', max_length=20, verbose_name='Тип доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='np_city_ref',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ref міста НП'),
        ),
        migrations.AddField(
            model_name='order',
            name='np_warehouse_ref',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ref відділення НП'),
        ),
    ]
