# Generated by Django 4.2.24 on 2025-11-13 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_delete_newsletter_delete_promotion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_ref', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Transaction ID')),
                ('order_data', models.JSONField(verbose_name='Дані замовлення')),
                ('is_processed', models.BooleanField(db_index=True, default=False, verbose_name='Оброблено')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('created_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order', verbose_name='Створене замовлення')),
            ],
            options={
                'verbose_name': 'Pending платіж',
                'verbose_name_plural': 'Pending платежі',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_ref', 'is_processed'], name='orders_pend_transac_031f65_idx'), models.Index(fields=['created_at'], name='orders_pend_created_ddc059_idx')],
            },
        ),
    ]
