# Generated by Django 4.2.21 on 2025-11-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_pendingpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_breakdown',
            field=models.JSONField(blank=True, default=dict, help_text='Детальна інформація про всі застосовані знижки', verbose_name='Розшифровка знижок'),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code_used',
            field=models.CharField(blank=True, default='', help_text='Промокод, який був застосований до замовлення', max_length=50, verbose_name='Використаний промокод'),
        ),
    ]
