services:
  - type: web
    name: beautyshop-django
    env: python
    plan: free
    buildCommand: bash build.sh
    startCommand: gunicorn beautyshop.wsgi:application --bind 0.0.0.0:$PORT --workers=1 --threads=4 --timeout=120 --max-requests=1000 --max-requests-jitter=50
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PYTHONHASHSEED
        value: random
      - key: MALLOC_ARENA_MAX
        value: 2
      - key: DATABASE_URL
        fromDatabase:
          name: beautyshop-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DJANGO_SETTINGS_MODULE
        value: beautyshop.settings.production
      - key: ALLOWED_HOSTS
        value: beautyshop-django.onrender.com,beautyshop-django-*.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://beautyshop-django.onrender.com,https://beautyshop-django-*.onrender.com
      - key: SITE_URL
        value: https://beautyshop-django.onrender.com
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PHONE
        value: +380681752654
      - key: CLOUDINARY_CLOUD_NAME
        value: dahkrj6ye
      - key: CLOUDINARY_API_KEY
        value: 232638167956413
      - key: CLOUDINARY_API_SECRET
        value: zn4vrWlnQoePX2k4PCtgGxhnrxk
      - key: AUTO_IMPORT_PRODUCTS
        value: true

databases:
  - name: beautyshop-db
    databaseName: beautyshop
    user: beautyshop_user
    plan: free