# Generated by Django 4.2.21 on 2025-10-28 12:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_delete_promotionproduct'),
        ('core', '0002_alter_banner_mobile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Контент')),
                ('excerpt', models.TextField(blank=True, max_length=300, verbose_name='Короткий опис')),
                ('image', models.ImageField(blank=True, upload_to='articles/', verbose_name='Зображення')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='SEO заголовок')),
                ('meta_description', models.TextField(blank=True, max_length=300, verbose_name='SEO опис')),
                ('related_products', models.ManyToManyField(blank=True, help_text='Максимум 5 товарів для відображення в кінці статті', limit_choices_to={'is_active': True}, to='products.product', verbose_name="Зв'язані товари")),
            ],
            options={
                'verbose_name': 'Стаття',
                'verbose_name_plural': 'Статті',
                'ordering': ['-created_at'],
            },
        ),
    ]
