# Generated by Django 4.2.21 on 2025-10-28 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='related_products',
        ),
    ]
