# Generated by Django 4.2.21 on 2025-10-28 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_related_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
