# Generated by Django 4.2.21 on 2025-10-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0008_add_sale_periods_and_new_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Промокод для введення користувачем', max_length=50, unique=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('discount_type', models.CharField(choices=[('percentage', 'Відсоток'), ('fixed', 'Фіксована сума')], default='percentage', max_length=20, verbose_name='Тип знижки')),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Відсоток або сума в гривнях', max_digits=10, verbose_name='Розмір знижки')),
                ('min_order_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Мінімальна сума для застосування промокоду', max_digits=10, null=True, verbose_name='Мінімальна сума замовлення')),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Залиште порожнім для необмеженої кількості', null=True, verbose_name='Максимум використань')),
                ('used_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Використано разів')),
                ('start_date', models.DateTimeField(verbose_name='Дата початку')),
                ('end_date', models.DateTimeField(verbose_name='Дата закінчення')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоди',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Буде відображатися на бейджі товару', max_length=100, verbose_name='Назва акції')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('retail_discount_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Відсоток знижки на роздрібну ціну', max_digits=5, null=True, verbose_name='Знижка для роздрібних (%)')),
                ('wholesale_discount_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Відсоток знижки на оптову ціну', max_digits=5, null=True, verbose_name='Знижка для оптових (%)')),
                ('qty3_discount_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Відсоток знижки на ціну від 3 шт', max_digits=5, null=True, verbose_name='Знижка від 3 шт (%)')),
                ('qty5_discount_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Відсоток знижки на ціну від 5 шт', max_digits=5, null=True, verbose_name='Знижка від 5 шт (%)')),
                ('start_date', models.DateTimeField(verbose_name='Дата початку')),
                ('end_date', models.DateTimeField(verbose_name='Дата закінчення')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Чим більше число, тим вищий пріоритет', verbose_name='Пріоритет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('categories', models.ManyToManyField(blank=True, help_text='Застосувати акцію до всіх товарів цих категорій', related_name='active_promotions', to='products.category', verbose_name='Категорії')),
                ('products', models.ManyToManyField(blank=True, related_name='active_promotions', to='products.product', verbose_name='Товари')),
            ],
            options={
                'verbose_name': 'Акція',
                'verbose_name_plural': 'Акції',
                'ordering': ['-priority', '-start_date'],
            },
        ),
    ]
