# Generated by Django 4.2.24 on 2025-11-12 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='description',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='is_active',
        ),
    ]
