# Generated by Django 4.2.21 on 2025-11-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(blank=True, help_text="Необов'язкове поле", max_length=100, verbose_name='По-батькові'),
        ),
    ]
