# Generated by Django 4.2.21 on 2025-11-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verification_attempts',
            field=models.IntegerField(default=0, verbose_name='Спроби введення коду'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_verification_code',
            field=models.CharField(blank=True, max_length=6, verbose_name='Код верифікації email'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_verification_code_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Час створення коду верифікації'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_reset_attempts',
            field=models.IntegerField(default=0, verbose_name='Спроби введення коду відновлення'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_reset_code',
            field=models.CharField(blank=True, max_length=6, verbose_name='Код відновлення паролю'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_reset_code_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Час створення коду відновлення'),
        ),
    ]
