# Generated by Django 4.2.21 on 2025-11-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_email_verification_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_wholesale',
            field=models.BooleanField(default=False, help_text='Встановлюється True після підтвердження email', verbose_name='Оптовий клієнт'),
        ),
    ]
