# Generated by Django 4.2.24 on 2025-11-08 13:38

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_is_wholesale'),
    ]

    operations = [
        migrations.CreateModel(
            name='WholesaleClient',
            fields=[
            ],
            options={
                'verbose_name': 'Оптовий клієнт',
                'verbose_name_plural': 'Оптові клієнти',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
